config:
  name: "products"
  target: "http://localhost:3000"
  phases:
    - duration: 30
      arrivalRate: 100
  ensure: 
        p95: 20
 
scenarios:
  - name: "Retrieve products"
    flow:
      - get:
          url: "/products"